{
  "formatVersion": "1.1",
  "component": {
    "group": "ir.mahozad",
    "module": "vlc-setup",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "vlc-setup-0.1.0.jar",
          "url": "vlc-setup-0.1.0.jar",
          "size": 872359,
          "sha512": "6712a9caced045021465cee13ef40eb735b64deb0367346e6d9f258ad19ad18995c80a116a0a50189279cf5af3804b66f1fa3e7c5170cb6522f6315d621361ab",
          "sha256": "6a29337744a4311af0b9dd21ab2e1071883c998f2c073b70db33005dd89d4639",
          "sha1": "34ac2b56f4ba068823749cd4663a15db196a192d",
          "md5": "a2e186e96fda0d8f789a8298fc75decb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.undercouch.download",
          "module": "de.undercouch.download.gradle.plugin",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "vlc-setup-0.1.0.jar",
          "url": "vlc-setup-0.1.0.jar",
          "size": 872359,
          "sha512": "6712a9caced045021465cee13ef40eb735b64deb0367346e6d9f258ad19ad18995c80a116a0a50189279cf5af3804b66f1fa3e7c5170cb6522f6315d621361ab",
          "sha256": "6a29337744a4311af0b9dd21ab2e1071883c998f2c073b70db33005dd89d4639",
          "sha1": "34ac2b56f4ba068823749cd4663a15db196a192d",
          "md5": "a2e186e96fda0d8f789a8298fc75decb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vlc-setup-0.1.0-javadoc.jar",
          "url": "vlc-setup-0.1.0-javadoc.jar",
          "size": 261,
          "sha512": "159fa3e50422a14e8a8372b396dbeb5ac0a7052ace191d5056dbdb85df73e6b5ca8a12159c32ebfe2f62473d9fdb26b41d915b5fe81092c819b65e5d354b198e",
          "sha256": "139668da847c66a11818557b022541bb161172002f641d67097f15181c452163",
          "sha1": "5be8c42073f85cb2c43824c49e6306b6bef4e83c",
          "md5": "9c80b1017e95091cc3217c9a5c7434a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vlc-setup-0.1.0-sources.jar",
          "url": "vlc-setup-0.1.0-sources.jar",
          "size": 818265,
          "sha512": "8bd854631ab07afb7b8a35b502607804a8d8f216890a26f1a50ce1183dbf85f52009a36f964c7ba10f7b5fef2a3d258b59aaa7a8aa3648c07263506e6ca8377b",
          "sha256": "a88828d9e6648562dfc1154f3696ffb484c71166554217bc15eb6148e7e87277",
          "sha1": "d423e0a3365787ea15c802e66ae329179f1fb653",
          "md5": "edaacb09446a733ea139e8a6835d4ca6"
        }
      ]
    }
  ]
}
